### ISSUE TITLE
Qt warning after exiting editor

### ISSUE THREAD

**Issue by bziemons** [istoph/editor#13]
When using the following config, I am getting multiple generic Qt warnings after exiting the editor.

log message(s):
```
Using QCharRef with an index pointing outside the valid range of a QString. The corresponding behavior is deprecated, and will be changed in a future version of Qt.
```

chr configuration:
```
color_space_end=true
color_tabs=true
highlight_bracket=true
right_margin_hint=80
tab=false
tabsize=8
theme=dark
wrap_lines=true
```

**Comment by textshell** [comment]
Thanks for reporting this reproducer.
With highlight_bracket=true empty lines trigger that message while processing bracket highlight.
I've fixed this cause of the error message in c1267820.
I'll close this issue for now.
But if you find another reproducible way to trigger these kind of error messages, please feel free to open another report.
