### ISSUE TITLE
debian package

### ISSUE THREAD

**Issue by alexmyczko** [istoph/editor#20]
http://bugs.debian.org/1059361

so is there already something to test?

**Comment by textshell** [comment]
Thanks for your interest in chr.

As you noticed we are currently working on getting packages into debian trixie.

If you are ok with building debian packages from source you can find what we currently have on mentors.debian.org and on salsa.

Currently you also need a updated version of tuiwidgets, that is waiting for a sponsored upload to debian.

tuiwidgets: [salsa](https://salsa.debian.org/chr/tuiwidgets) [mentors](https://mentors.debian.net/package/tuiwidgets/) [Debian Sponsor Request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057974)

chr: [salsa](https://salsa.debian.org/chr/chr/) [mentors](https://mentors.debian.net/package/chr/)

If you looking for a quick way to install, without building from source or are not running debian sid/trixie/bookworm you can have a look at @istoph's package repository (which also contains other packages)

https://blog.chr.istoph.de/repository/

That repo has binary only packages that are not build in "the debian way" at the moment and also gets development releases as the software develops (not quite nightly builds but also not releases).

It also has packages for Ubuntu, RHEL, Fedora and Arch)

If you are looking for packages for ubuntu, there is a work in progress ppa here:

https://launchpad.net/~chr-istoph/+archive/ubuntu/chr

(noble numbat only for now)

**Comment by alexmyczko** [comment]
Once it is in Debian, you don't care about Ubuntu as they will archive sync from Debian sid...
Let's see: https://ftp-master.debian.org/new/chr_0.1.77-1.html
Great someone put the dep: https://repology.org/project/tuiwidgets/versions

**Comment by textshell** [comment]
Thanks for sponsoring chr.

I fear we will be missing the debian import freeze for ubuntu 24.04, still having to clear NEW and testing migration. So for 20.04 it seems the ppa will be still needed. And is was soo close.

**Comment by alexmyczko** [comment]
testing migration is not needed. ubuntu syncy from sid, sometimes even from experimental… just because the auto sync is stopped means nothing, still can request sync. but then hey it is in debian! use debian, and we can do debian backports.

**Comment by textshell** [comment]
From what i understand LTS releases of ubuntu sync from testing. But if you think it could be successful, we might try to ask motu to sync when the package has cleared NEW. Lets hope for fast NEW processing.

**Comment by alexmyczko** [comment]
haha :) good luck.
