### ISSUE TITLE
Selecting text and trying to override with a capital S results in adding a capital S instead

### ISSUE THREAD

**Issue by bziemons** [istoph/editor#7]
Screencast showing the issue:

https://user-images.githubusercontent.com/1096713/222402118-9c13c063-b3de-4c73-8f22-114d8192f4cf.mp4

**Comment by bziemons** [comment]
Fixed in most recent commit(s) of termpaint, tuiwidgets and the editor.

**Comment by textshell** [comment]
I think this was one of the problems fixed by d0753f98.
